### ISSUE TITLE
allow second / in path to pass

### ISSUE THREAD

**Issue by Maurice-Roy** [learn-co-curriculum/sinatra-basic-routes-lab#7]
Please let '/name/' also pass for the path instead of just '/name' etc. Seems unintuitive & many lessons before this have recommended including the second /.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. Ideally, the application should be able to handle both `/name/` and `/name`. You can use the [trailing slash](http://sinatrarb.com/faq.html#slash) in Sinatra to handle both urls.

As always thank you for contributing!
